"""initial

Revision ID: 2549f950b99c
Revises: 
Create Date: 2026-03-02 08:59:12.290531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2549f950b99c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpci_localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=10), nullable=True),
    sa.Column('locality_number', sa.String(length=10), nullable=False),
    sa.Column('locality_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('work_gpci', sa.Float(), nullable=False),
    sa.Column('pe_gpci', sa.Float(), nullable=False),
    sa.Column('mp_gpci', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpci_localities_locality_number'), 'gpci_localities', ['locality_number'], unique=False)
    op.create_table('medicare_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('modifier', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('work_rvu', sa.Float(), nullable=False),
    sa.Column('pe_rvu_facility', sa.Float(), nullable=False),
    sa.Column('pe_rvu_nonfacility', sa.Float(), nullable=False),
    sa.Column('mp_rvu', sa.Float(), nullable=False),
    sa.Column('status_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicare_rates_cpt_code'), 'medicare_rates', ['cpt_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zip_localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('carrier', sa.String(length=10), nullable=True),
    sa.Column('locality', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_localities_zip_code'), 'zip_localities', ['zip_code'], unique=False)
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('gpci_locality', sa.String(length=10), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'extracting', 'review', 'compared', 'error', name='contractstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('modifier', sa.String(length=10), nullable=True),
    sa.Column('contracted_rate', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('medicare_rate', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('pct_of_medicare', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_rates_cpt_code'), 'contract_rates', ['cpt_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_rates_cpt_code'), table_name='contract_rates')
    op.drop_table('contract_rates')
    op.drop_table('contracts')
    op.drop_table('practices')
    op.drop_index(op.f('ix_zip_localities_zip_code'), table_name='zip_localities')
    op.drop_table('zip_localities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_medicare_rates_cpt_code'), table_name='medicare_rates')
    op.drop_table('medicare_rates')
    op.drop_index(op.f('ix_gpci_localities_locality_number'), table_name='gpci_localities')
    op.drop_table('gpci_localities')
    # ### end Alembic commands ###
