"""add gpci_carrier to practices

Revision ID: 724548b35af2
Revises: 2549f950b99c
Create Date: 2026-03-02 10:32:41.617251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724548b35af2'
down_revision: Union[str, Sequence[str], None] = '2549f950b99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('gpci_carrier', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practices', 'gpci_carrier')
    # ### end Alembic commands ###
