"""add lab_fee_schedule and utilization tables

Revision ID: ba88eea74ebd
Revises: 724548b35af2
Create Date: 2026-03-02 14:05:09.231013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba88eea74ebd'
down_revision: Union[str, Sequence[str], None] = '724548b35af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_fee_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('modifier', sa.String(length=10), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_fee_schedule_cpt_code'), 'lab_fee_schedule', ['cpt_code'], unique=False)
    op.create_table('utilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('total_services', sa.Integer(), nullable=False),
    sa.Column('total_allowed', sa.Float(), nullable=False),
    sa.Column('total_payment', sa.Float(), nullable=False),
    sa.Column('avg_allowed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilization_cpt_code'), 'utilization', ['cpt_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilization_cpt_code'), table_name='utilization')
    op.drop_table('utilization')
    op.drop_index(op.f('ix_lab_fee_schedule_cpt_code'), table_name='lab_fee_schedule')
    op.drop_table('lab_fee_schedule')
    # ### end Alembic commands ###
